# -*- coding: utf-8 -*-
"""movie_recommendation_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XxpPVxSEEJZYqLoUwRxE7iDfqFvO-vND
"""

import numpy as np
import pandas as pd

movies= pd.read_csv('tmdb_5000_movies.csv')
credits= pd.read_csv('tmdb_5000_credits.csv')

movies.head(1)

credits.head(1)

movies= movies.merge(credits, on ='title')

movies.head(1)

movies=movies[['movie_id', 'title' , 'overview' , 'genres' , 'keywords' , 'cast' , 'crew']]

movies.isnull().sum()

movies.dropna(inplace= True)

movies.duplicated().sum()

import ast
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

movies['genres']= movies['genres'].apply(convert)

movies['keywords']= movies['keywords'].apply(convert)

movies.head()

import ast
def convert_cast(obj):
  L=[]
  counter = 0
  for i in ast.literal_eval (obj):
    if counter !=3 :
       L.append(i['name'])
       counter +=1
    else:
      break
  return L

movies['cast']= movies['cast'].apply(convert_cast)

def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

movies['crew']= movies['crew'].apply(fetch_director)

movies['overview']= movies['overview'].apply(lambda x:x.split())

movies['genres']= movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords']= movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast']= movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew']= movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

movies['tags']= movies['overview']+ movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

new_df = movies[['movie_id', 'title', 'tags']]

new_df

new_df['tags']= new_df['tags'].apply(lambda x:" ".join(x))

new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features= 5000 , stop_words='english')

vectors= cv.fit_transform(new_df['tags']).toarray()

cv.get_feature_names_out()

import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
  y = []
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

new_df['tags']= new_df['tags'].apply(stem)

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

def recommend(movie):
  movie=movie.strip()
  if movie not in new_df['title'].values:
    print("Movie not found in dataset.")
    return
  movie_index=new_df[new_df['title']==movie].index[0]
  distances= similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)),reverse=True, key = lambda x:x[1])[1:6]
  print(f"\nMovies similar to '{movie}' are :\n")
  for i in movies_list:
    print (new_df.iloc[i[0]].title)

movie_name = input("Enter a movie you like: ")
recommend(movie_name)