# -*- coding: utf-8 -*-
"""dog vs cat classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RRanLiLzieI6DhhNVpcc6ZN2mvGqRIPm
"""


!kaggle datasets download -d chetankv/dogs-cats-images

import zipfile
zip_ref= zipfile.ZipFile('/content/dogs-cats-images.zip', 'r')
zip_ref.extractall('/content')
zip_ref.close()

import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten , BatchNormalization ,Dropout

train_ds = keras.utils.image_dataset_from_directory(
    directory='/content/dog vs cat/dataset/training_set',
    labels='inferred',
    label_mode='int',
    batch_size=32,
    image_size=(256, 256)
)

test_ds = keras.utils.image_dataset_from_directory(
    directory='/content/dog vs cat/dataset/test_set',
    labels='inferred',
    label_mode='int',
    batch_size=32,
    image_size=(256, 256)
)

def process(image, label):
  image = tf.cast(image/255. , tf.float32)
  return image,label
train_ds= train_ds.map(process)
test_ds = test_ds.map(process)

model = Sequential()

model.add(Conv2D(32, kernel_size=(3,3), padding='valid', activation='relu', input_shape=(256,256,3)))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2), strides=2, padding='valid'))

model.add(Conv2D(64, kernel_size=(3,3), padding='valid', activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2), strides=2, padding='valid'))

model.add(Conv2D(128, kernel_size=(3,3), padding='valid', activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2), strides=2, padding='valid'))

model.add(Flatten())

model.add(Dense(128, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(1, activation='sigmoid'))

model.summary()

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=10
)

loss, accuracy = model.evaluate(test_ds)
print("Test Accuracy:", accuracy)

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'], color='red', label='train')
plt.plot(history.history['val_accuracy'], color='blue', label='validation')
plt.legend()
plt.show()

plt.plot(history.history['loss'], color='red', label='train')
plt.plot(history.history['val_loss'], color='blue', label='validation')
plt.legend()
plt.show()

import numpy as np
import cv2

# Load image (change path to your test image)
test_img = cv2.imread('/content/sample_cat.jpg')


test_img = cv2.resize(test_img, (256, 256))


test_img = test_img / 255.0

test_img = np.expand_dims(test_img, axis=0)


prediction = model.predict(test_img)

if prediction[0][0] > 0.5:
    print("Prediction: DOG")
else:
    print("Prediction: CAT")